[package]
name = "staking-bank-static-dev-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.staking-bank-static-dev]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.41.3"
