// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    umbrella_example
    (
        init => init
        pay => pay
        collect => collect
        getExternalPriceData => get_external_price_data
        getExternalPrice => get_external_price
        registry => registry
        token_identifier => token_identifier
        token_key => token_key
        last_collect_time => last_collect_time
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
