// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           16
// Async Callback (empty):               1
// Total number of exported functions:  18

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    umbrella_feeds
    (
        init => init
        upgrade => upgrade
        update => update
        getManyPriceData => get_many_price_data
        getManyPriceDataRaw => get_many_price_data_raw
        getPriceData => get_price_data
        getPrice => get_price
        getPriceTimestamp => get_price_timestamp
        getPriceTimestampHeartbeat => get_price_timestamp_heartbeat
        getPriceDataByName => get_price_data_by_name
        hashData => hash_data
        verifySignatures => verify_signatures
        prices => prices
        required_signatures => required_signatures
        decimals => decimals
        chain_id => chain_id
        staking_bank => staking_bank
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
