// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback:                       1
// Total number of exported functions:  10

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    time_lock
    (
        init => init
        upgrade => upgrade
        proposeCall => propose_call
        discardLastCall => discard_last_call
        discardNextCall => discard_next_call
        performNextCall => perform_next_call
        getTimeLockPeriod => time_lock_period
        getMultisigAddress => multisig_address
        getPendingCallsFullInfo => call_data_mapper
    )
}

multiversx_sc_wasm_adapter::async_callback! { time_lock }
