[package]
name = "umbrella-example-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.umbrella-example]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.47.4"
