name: Build and attach artifacts for development

on:
  pull_request:
    branches: [ develop ]

permissions:
  contents: write

jobs:
  build_registry:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@v2.3.5
    with:
      image_tag: v6.1.0
      attach_to_existing_release: false
      package_whole_project_src: true
      contract_name: registry

  build_bank_dev:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@v2.3.5
    with:
      image_tag: v6.1.0
      attach_to_existing_release: false
      package_whole_project_src: true
      contract_name: staking-bank-static-dev

  build_bank_sbx:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@v2.3.5
    with:
      image_tag: v6.1.0
      attach_to_existing_release: false
      package_whole_project_src: true
      contract_name: staking-bank-static-sbx

  build_timelock:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@v2.3.5
    with:
      image_tag: v6.1.0
      attach_to_existing_release: false
      package_whole_project_src: true
      contract_name: time-lock

  build_feeds:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@v2.3.5
    with:
      image_tag: v6.1.0
      attach_to_existing_release: false
      package_whole_project_src: true
      contract_name: umbrella-feeds
