name: Pre-release build and attach artifacts

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build_registry:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@v2.3.5
    with:
      image_tag: v6.1.0
      attach_to_existing_release: false
      package_whole_project_src: true
      contract_name: registry

  build_bank_prod:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@v2.3.5
    with:
      image_tag: v6.1.0
      attach_to_existing_release: false
      package_whole_project_src: true
      contract_name: staking-bank-static-prod

  build_timelock:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@v2.3.5
    with:
      image_tag: v6.1.0
      attach_to_existing_release: false
      package_whole_project_src: true
      contract_name: time-lock

  build_feeds:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@v2.3.5
    with:
      image_tag: v6.1.0
      attach_to_existing_release: false
      package_whole_project_src: true
      contract_name: umbrella-feeds
