name: Pre-release build and attach artifacts

on:
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: write

jobs:
  pre_build_contracts:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@v4.2.2
    with:
      image_tag: v8.0.0
      attach_to_existing_release: false
      package_whole_project_src: true
