name: On release, build contracts

on:
  release:
    types: [published]
  pull_request:
    branches: [ main, develop, feature/* ]
    
permissions:
  contents: write

jobs:
  build_contracts:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@v3.2.0
    with:
      image_tag: v8.0.0
      attach_to_existing_release: true
      package_whole_project_src: true
