name: On release build and attach artifacts

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@v2.3.1
    with:
      image_tag: v5.2.0
      attach_to_existing_release: true